# Generated by Django 4.0.7 on 2022-12-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('postal', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('postal', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('vacancies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sheltered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('ethnicity', models.CharField(max_length=30)),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelter', to='shelters.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='ShelterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_shelter', to='shelters.device')),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelter_device', to='shelters.shelter')),
            ],
        ),
    ]
