# Generated by Django 4.0.7 on 2022-12-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_rename_name_shelter_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='postal',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='city',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='district',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='code',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='address',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='number',
            new_name='número',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='city',
            new_name='Bairro',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='postal',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='district',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='number',
            new_name='Vagas',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='address',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='vacancies',
            new_name='número',
        ),
        migrations.RenameField(
            model_name='shelterdevice',
            old_name='shelter',
            new_name='abrigo',
        ),
        migrations.RenameField(
            model_name='shelterdevice',
            old_name='device',
            new_name='dispositivo',
        ),
        migrations.RenameField(
            model_name='shelterdevice',
            old_name='distance',
            new_name='distância',
        ),
        migrations.RenameField(
            model_name='sheltered',
            old_name='shelter',
            new_name='abrigo',
        ),
        migrations.RenameField(
            model_name='sheltered',
            old_name='ethnicity',
            new_name='etinia',
        ),
        migrations.RenameField(
            model_name='sheltered',
            old_name='genre',
            new_name='gênero',
        ),
        migrations.RenameField(
            model_name='sheltered',
            old_name='age',
            new_name='idade',
        ),
        migrations.RenameField(
            model_name='sheltered',
            old_name='name',
            new_name='nome',
        ),
    ]
