# Generated by Django 4.0.7 on 2022-12-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_rename_bairro_shelter_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
