# Generated by Django 4.0.7 on 2022-12-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0006_shelter_ocupação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='ocupação',
            new_name='vacância',
        ),
    ]
