# Generated by Django 4.0.7 on 2022-12-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0007_rename_ocupação_shelter_vacância'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='pet',
            field=models.CharField(default='Não', max_length=5),
        ),
    ]
