# Generated by Django 4.0.7 on 2022-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0008_shelter_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='abrigo',
            field=models.ManyToManyField(blank=True, related_name='abrigo', to='shelters.shelter'),
        ),
    ]
