# Generated by Django 4.0.7 on 2022-12-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0009_device_abrigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='endereço',
            new_name='endereço_dispositivo',
        ),
    ]
