# Generated by Django 4.0.7 on 2022-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0011_remove_device_abrigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='abrigo',
            field=models.ManyToManyField(blank=True, related_name='shelterdevice', to='shelters.shelter'),
        ),
    ]
