# Generated by Django 4.0.7 on 2022-12-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0012_device_abrigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='número',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='número',
        ),
    ]
