version: '3.9'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn django_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=d4!vt75oy9l6#l8nt!b-spnl@3i0(s6+ykb!rikb!lg#_myh=)4"
      - "DJANGO_DEBUG=False"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

#  pgadmin:
#    image: dpage/pgadmin4:6.10
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: triptolemo@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: postgres
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "8080:80"
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    links:
#      - "db:pgsql-server"

#volumes:
#  pgadmin_data: